name: Build SSCMS-PluginShell

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore SSCMS.Advertisement.csproj
    
    - name: Build project
      run: dotnet build SSCMS.Advertisement.csproj --configuration Release --no-restore
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: '**/bin/Release/**/*'
